[project]
name = "msfs-simrate-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "pyinstaller>=6.18.0",
    "pywin32>=311",
    "winshell>=0.6",
]
